name: Go Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Build and test
      run: |
        go mod download
        go build -v ./...
        go test -v ./...
